apiVersion: v1
kind: Service
metadata:
  labels:
    app: pricelist
    tier: frontend
  name: pricelist
  namespace: pricelist
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pricelist
    tier: frontend
  type: LoadBalancer
